version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    env_file: db.env
    volumes:
      - upb-db-data:/var/lib/mysql

  dbadmin:
    image: phpmyadmin:5.2.0
    restart: unless-stopped
    ports:
      - "8080:80"
    env_file: dbadmin.env

  api:
    depends_on:
      - db
    image: ghcr.io/martinsiran/upb-webapp/api:latest
    restart: unless-stopped
    env_file: api.env
    ports:
      - "5000:5000"

  fe:
    image: ghcr.io/martinsiran/upb-webapp/fe:latest
    restart: unless-stopped
    ports:
      - "3000:3000"

volumes:
  upb-db-data:
